spring:
 application:
  name: api-gateway

server:  port: 9000

eureka:
  client:
    service-url:
       default-zone: http://localhost:8761/eureka**

zuul:
  routes:
    userservice:
      path: /user/**
      service-id: USER-MICROSERVICE
#      url: USER-MICROSERVICE
      strip-prefix: false